### ISSUE TITLE
运行examples/sft/finetune.sh报错，请问用的环境版本分别是多少的呢？

### ISSUE THREAD

**Issue by sxk000** [QwenLM/Qwen2#183]
首先，感谢分享！

用的机器是单机多卡，8*A800，centos7，cuda12.2.2，python3.12.2,

Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1160.el7.x86_64
Architecture: x86-64

具体操作步骤如下：
1，pip3 install torch torchvision torchaudio，自动安装的torch-2.2.1
2，pip3 install deepspeed，自动安装的deepspeed-0.14.0
3，pip3 install transformers，自动安装的transformers-4.38.2
4，pip3 install peft，自动安装的peft-0.9.0

数据集格式按照  https://github.com/QwenLM/Qwen1.5/issues/156  的提示，
用的 https://qwen.readthedocs.io/zh-cn/latest/training/SFT/example.html 中提到的如下格式：
```
准备数据
我们建议你放在jsonl文件中，每一行是一个如下所示的字典：

{
    "type": "chatml",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "Tell me something about large language models."
        },
        {
            "role": "assistant",
            "content": "Large language models are a type of language model that is trained on a large corpus of text data. They are capable of generating human-like text and are used in a variety of natural language processing tasks..."
        }
    ],
    "source": "unknown"
}
```

用的模型：MODEL="/apply/model/original/Qwen1.5-14B-Chat"

运行微调命令：sh finetune.sh

报如下错误：

```
sh finetune.sh
[2024-03-18 20:18:16,169] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-18 20:18:16,900] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-03-18 20:18:16,900] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-03-18 20:18:17,633] [INFO] [partition_parameters.py:343:__exit__] finished initializing model - num_params = 483, num_elems = 14.17B
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.17s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading data...
Formatting inputs...Skip in lazy mode
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Using /root/.cache/torch_extensions/py312_cu121 as PyTorch extensions root...
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py:388: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
Detected CUDA files, patching ldflags
Traceback (most recent call last):
  File "/apply/app/llm/qwen/finetune.py", line 375, in <module>
    train()
  File "/apply/app/llm/qwen/finetune.py", line 366, in train
    trainer.train()
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/trainer.py", line 1779, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py", line 1255, in prepare
    result = self._prepare_deepspeed(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
                ^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    op_module = load(name=self.name,
                ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1800, in _write_ninja_file_and_build_library
    extra_ldflags = _prepare_ldflags(
                    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1893, in _prepare_ldflags
    if (not os.path.exists(_join_cuda_home(extra_lib_dir)) and
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2407, in _join_cuda_home
    raise OSError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
[2024-03-18 20:18:29,377] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 37280) of binary: /root/miniconda3/envs/p312qwen1.5/bin/python3.12
Traceback (most recent call last):
  File "/root/miniconda3/envs/p312qwen1.5/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-18_20:18:29
  host      : h3c-1st-mysteel-algorithm2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 37280)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

请问这个问题该如何解决呢？

再次感谢！

**Comment by sxk000** [comment]
conda install -c psi4 gcc-5

解决gcc的下面问题：
```

                           !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++ 4.8.5) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 5.0 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 5 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!
```

**Comment by sxk000** [comment]
目前报错如下：

```
sh finetune.sh 
[2024-03-19 11:08:19,740] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-03-19 11:08:20,506] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-03-19 11:08:20,507] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-03-19 11:08:21,247] [INFO] [partition_parameters.py:343:__exit__] finished initializing model - num_params = 483, num_elems = 14.17B
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.24s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading data...
Formatting inputs...Skip in lazy mode
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py:432: FutureWarning: Passing the following arguments to `Accelerator` is deprecated and will be removed in version 1.0 of Accelerate: dict_keys(['dispatch_batches', 'split_batches', 'even_batches', 'use_seedable_sampler']). Please pass an `accelerate.DataLoaderConfiguration` instead: 
dataloader_config = DataLoaderConfiguration(dispatch_batches=None, split_batches=False, even_batches=True, use_seedable_sampler=True)
  warnings.warn(
Detected kernel version 3.10.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Using /root/.cache/torch_extensions/py312_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py312_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda-12.2/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/TH -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-12.2/include -isystem /root/miniconda3/envs/p312qwen1.5/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/local/cuda-12.2/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/TH -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-12.2/include -isystem /root/miniconda3/envs/p312qwen1.5/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_80,code=compute_80 -gencode=arch=compute_80,code=sm_80 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_80,code=sm_80 -gencode=arch=compute_80,code=compute_80 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc warning : The -std=c++17 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:0:
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/ATen.h:4:2: error: #error C++17 or later compatible compiler is required to use ATen.
 #error C++17 or later compatible compiler is required to use ATen.
  ^
In file included from /root/miniconda3/envs/p312qwen1.5/gcc/include/c++/mutex:35:0,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/core/Generator.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/Context.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/ATen.h:7,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/root/miniconda3/envs/p312qwen1.5/gcc/include/c++/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/StringUtil.h:6:0,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/Exception.h:5,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/core/Generator.h:11,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/Context.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/ATen.h:7,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu:11:
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/string_view.h:10:23: fatal error: string_view: No such file or directory
compilation terminated.
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/TH -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-12.2/include -isystem /root/miniconda3/envs/p312qwen1.5/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DBF16_AVAILABLE -c /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
FAILED: fused_adam_frontend.o 
c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/includes -I/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/TH -isystem /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/THC -isystem /usr/local/cuda-12.2/include -isystem /root/miniconda3/envs/p312qwen1.5/include/python3.12 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DBF16_AVAILABLE -c /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
In file included from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/extension.h:5:0,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp:6:
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include/torch/all.h:4:2: error: #error C++17 or later compatible compiler is required to use PyTorch.
 #error C++17 or later compatible compiler is required to use PyTorch.
  ^
In file included from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/StringUtil.h:6:0,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/Exception.h:5,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/core/Device.h:5,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/core/TensorBody.h:11,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/ATen/Tensor.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/torch/extension.h:5,
                 from /root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp:6:
/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/include/c10/util/string_view.h:10:23: fatal error: string_view: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/apply/app/llm/qwen/finetune.py", line 375, in <module>
    train()
  File "/apply/app/llm/qwen/finetune.py", line 366, in train
    trainer.train()
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/transformers/trainer.py", line 1779, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py", line 1255, in prepare
    result = self._prepare_deepspeed(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/accelerate/accelerator.py", line 1640, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
                ^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    op_module = load(name=self.name,
                ^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/utils/cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
[2024-03-19 11:08:32,845] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 103766) of binary: /root/miniconda3/envs/p312qwen1.5/bin/python3.12
Traceback (most recent call last):
  File "/root/miniconda3/envs/p312qwen1.5/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/p312qwen1.5/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-19_11:08:32
  host      : h3c-1st-mysteel-algorithm2
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 103766)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

请问这个问题该如何解决呢？

感谢！

**Comment by littlewwwhite** [comment]
同问，也是这里报错

**Comment by Autism-al** [comment]
同问，我也遇到了这个问题，用最新版的GCC仍然报错

**Comment by Autism-al** [comment]
我解决了。conda search gcc和gxx，分别选一个合适的版本安装即可，版本要一致。我用的是10.3.0，可以跑起来。

**Comment by gg22mm** [comment]
确实是gcc太旧的原因
