### ISSUE TITLE
Qwen1.5-0.5B-Chat推理的时候出现：RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cpu! (when checking argument for argument index in method wrapper__index_select)

### ISSUE THREAD

**Issue by 15024287710Jackson** [QwenLM/Qwen2#341]
推理代码：

```
def qwen_inference():
    # Now you do not need to add "trust_remote_code=True"
    model = AutoModelForCausalLM.from_pretrained(
        "/home/ma-user/work/Qwen1.5-0.5B-Chat2",
        torch_dtype="auto",
        device_map="auto"
    )
    tokenizer = AutoTokenizer.from_pretrained("/home/ma-user/work/Qwen1.5-0.5B-Chat2")
    device = torch.device("cuda")
    user_prompt = "你是广东省人民政府办公厅的工作人员，请生成一篇标题为“广东省数字政府建设实施意见”，关键词包括民生服务、数字平台、数字办公、一网统管、一网通办，年份信息为2023年的公文。"
    prompt = {}
    messages = []
    # system
    messages_system = {}
    messages_system["role"] = "system"
    messages_system["content"] = "You are a helpful assistant."
    # user+question
    messages_user = {}
    messages_user["role"] = "user"
    messages_user["content"] = user_prompt
    messages.append(messages_system)
    messages.append(messages_user)
    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    model_inputs = tokenizer([text], return_tensors="pt").to(device)
    generated_ids = model.generate(
        model_inputs.input_ids,
        max_new_tokens=10000
    )
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    print(response)
```
推理卡：8*32GV100

```
print(torch.__version__) ：  1.13.1+cu116
```
报错信息：

```
(Qwen-env) [ma-user inference]$python Qwen_infer_test01.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "Qwen_infer_test01.py", line 71, in <module>
    qwen_inference()
  File "Qwen_infer_test01.py", line 51, in qwen_inference
    generated_ids = model.generate(
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/transformers/generation/utils.py", line 1575, in generate
    result = self._sample(
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/transformers/generation/utils.py", line 2697, in _sample
    outputs = self(
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1173, in forward
    outputs = self.model(
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/transformers/models/qwen2/modeling_qwen2.py", line 1003, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/home/ma-user/anaconda3/envs/Qwen-env/lib/python3.8/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:7 and cuda:0! (when checking argument for argument index in method wrapper__index_select)
```

**Comment by 15024287710Jackson** [comment]
4B，7B和1.8B都不会有这个问题，0.5B和0.5B-chat就出现了

**Comment by cooper12121** [comment]
> 4B，7B和1.8B都不会有这个问题，0.5B和0.5B-chat就出现了

训别的模型遇到过，应该是deespeed版本的问题，更新，如果0.14.1版本不行可以试试0.14.0

**Comment by jklj077** [comment]
It seems that the input tensor is on a different device from the embedding layer. Normally, they should both on device 0, but currently one is on device 7. As a temporary solution, try moving the input to the same device as the embedding layer. For example, `model_inputs.to(model.model.embed_tokens.device)`

P.S.: Your `torch` and CUDA is rather old; please consider upgrading.

**Comment by 15024287710Jackson** [comment]
Thank you. I just added this   “os.environ["CUDA_VISIBLE_DEVICES"] = "1"” which can solve my problem. 

By this way, I want to know how to add the “model_inputs.to(model.model.embed_tokens.device)” into the code that I post, can you point out where I add this sequence into my code?
