### ISSUE TITLE
vllm加载qwen moe gptq int4量化模型

### ISSUE THREAD

**Issue by nieallen** [QwenLM/Qwen2#449]
请问未来可以支持量化版本的moe模型的vllm推理吗

**Comment by jklj077** [comment]
Hi, may I know what errors you have met?

**Comment by nieallen** [comment]
I noticed that vllm does not support inference for the quantized versions of qwen-moe awq or gptq in a previous issue.  Is it supported now?

**Comment by nieallen** [comment]
Traceback (most recent call last):
  File "examples/vllm_inference_qwen.py", line 23, in <module>
    llm = LLM(model=qwen_model, gpu_memory_utilization=0.6, quantization="gptq")
  File "/opt/conda/lib/python3.8/site-packages/vllm/entrypoints/llm.py", line 112, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 196, in from_engine_args
    engine = cls(
  File "/opt/conda/lib/python3.8/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/opt/conda/lib/python3.8/site-packages/vllm/executor/gpu_executor.py", line 37, in __init__
    self._init_worker()
  File "/opt/conda/lib/python3.8/site-packages/vllm/executor/gpu_executor.py", line 66, in _init_worker
    self.driver_worker.load_model()
  File "/opt/conda/lib/python3.8/site-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/opt/conda/lib/python3.8/site-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/model_loader.py", line 91, in get_model
    model = model_class(model_config.hf_config, linear_method)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 378, in __init__
    self.model = Qwen2MoeModel(config, linear_method)
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 342, in __init__
    self.layers = nn.ModuleList([
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 343, in <listcomp>
    Qwen2MoeDecoderLayer(config,
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 284, in __init__
    self.mlp = Qwen2MoeSparseMoeBlock(config=config,
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 114, in __init__
    self.pack_params()
  File "/opt/conda/lib/python3.8/site-packages/vllm/model_executor/models/qwen2_moe.py", line 138, in pack_params
    w1.append(expert.gate_up_proj.weight)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MergedColumnParallelLinear' object has no attribute 'weight'

**Comment by jklj077** [comment]
Hi, thanks for the error logs. It is being implemented (mainly because of efficiency issues) but we must say it will take some time. Right now, I would suggest to use the non-quantized version with vllm if the condition permits.
