### ISSUE TITLE
Fine-Tuning Qwen/Qwen2-1.5B: Missing Keys in state_dict

### ISSUE THREAD

**Issue by Li-Boqiang** [QwenLM/Qwen2#682]
Hi,

I am encountering an issue while trying to fine-tune the Qwen/Qwen2-1.5B model using the finetune.sh script. The process fails with errors indicating missing keys in the state_dict. Below are the steps I followed and the error details:

Run the fine-tuning command:
```
bash finetune.sh -m Qwen/Qwen2-1.5B -d /home/wind/Qwen2/dataset/fastchat.jsonl
```

The script begins execution but fails with the following traceback:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/wind/Qwen2/examples/sft/finetune.py", line 383, in <module>
[rank0]:     train()
[rank0]:   File "/home/wind/Qwen2/examples/sft/finetune.py", line 372, in train
[rank0]:     trainer.train(resume_from_checkpoint=True)
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/transformers/trainer.py", line 1885, in train
[rank0]:     return inner_training_loop(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/transformers/trainer.py", line 2063, in _inner_training_loop
[rank0]:     deepspeed_load_checkpoint(
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/transformers/integrations/deepspeed.py", line 432, in deepspeed_load_checkpoint
[rank0]:     load_path, _ = deepspeed_engine.load_checkpoint(
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2764, in load_checkpoint
[rank0]:     load_path, client_states = self._load_checkpoint(load_dir,
[rank0]:                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2847, in _load_checkpoint
[rank0]:     self.load_module_state_dict(checkpoint=checkpoint,
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/deepspeed/runtime/engine.py", line 2627, in load_module_state_dict
[rank0]:     self.module.load_state_dict(
[rank0]:   File "/home/wind/.conda/envs/Qwen2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
[rank0]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank0]: RuntimeError: Error(s) in loading state_dict for Qwen2ForCausalLM:
[rank0]:        Missing key(s) in state_dict: "model.layers.24.self_attn.q_proj.weight", "model.layers.24.self_attn.q_proj.bias", "model.layers.24.self_attn.k_proj.weight", "model.layern.k_proj.bias", "model.layers.24.self_attn.v_proj.weight", "model.layers.24.self_attn.v_proj.bias", "model.layers.24.self_attn.o_proj.weight", "model.layers.24.mlp.gate_proj.weight", "m4.mlp.up_proj.weight", "model.layers.24.mlp.down_proj.weight", "model.layers.24.input_layernorm.weight", "model.layers.24.post_attention_layernorm.weight", "model.layers.25.self_attn.q_ "model.layers.25.self_attn.q_proj.bias", "model.layers.25.self_attn.k_proj.weight", "model.layers.25.self_attn.k_proj.bias", "model.layers.25.self_attn.v_proj.weight", "model.layers.25proj.bias", "model.layers.25.self_attn.o_proj.weight", "model.layers.25.mlp.gate_proj.weight", "model.layers.25.mlp.up_proj.weight", "model.layers.25.mlp.down_proj.weight", "model.layeryernorm.weight", "model.layers.25.post_attention_layernorm.weight", "model.layers.26.self_attn.q_proj.weight", "model.layers.26.self_attn.q_proj.bias", "model.layers.26.self_attn.k_projdel.layers.26.self_attn.k_proj.bias", "model.layers.26.self_attn.v_proj.weight", "model.layers.26.self_attn.v_proj.bias", "model.layers.26.self_attn.o_proj.weight", "model.layers.26.mlpight", "model.layers.26.mlp.up_proj.weight", "model.layers.26.mlp.down_proj.weight", "model.layers.26.input_layernorm.weight", "model.layers.26.post_attention_layernorm.weight", "model.f_attn.q_proj.weight", "model.layers.27.self_attn.q_proj.bias", "model.layers.27.self_attn.k_proj.weight", "model.layers.27.self_attn.k_proj.bias", "model.layers.27.self_attn.v_proj.weilayers.27.self_attn.v_proj.bias", "model.layers.27.self_attn.o_proj.weight", "model.layers.27.mlp.gate_proj.weight", "model.layers.27.mlp.up_proj.weight", "model.layers.27.mlp.down_projdel.layers.27.input_layernorm.weight", "model.layers.27.post_attention_layernorm.weight".
```

Additional Information:

 - Transformers version: 4.41.2
 - PyTorch version: 2.3.0
 - DeepSpeed version: 0.14.2
 - Python version: 3.11

Could you please help me understand why these keys are missing and how to resolve this issue? Any guidance on how to correctly fine-tune the model with the given checkpoint would be greatly appreciated.

Thank you in advance for your assistance!

**Comment by Li-Boqiang** [comment]
After deleting the existing checkpoint, it returns to normal.
