### ISSUE TITLE
Qwen2中运行examples/sft中的代码报错torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by CmyLjj** [QwenLM/Qwen2#697]
```
[W socket.cpp:426] [c10d] The server socket cannot be initialized on [::]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[2024-06-24 13:47:48,006] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-06-24 13:47:49,838] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-24 13:47:49,838] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:601] [c10d] The client socket cannot be initialized to connect to [localhost]:6001 (errno: 97 - Address family not supported by protocol).
[2024-06-24 13:47:50,667] [INFO] [partition_parameters.py:343:__exit__] finished initializing model - num_params = 339, num_elems = 7.62B
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:12<00:00,  3.08s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
trainable params: 161,480,704 || all params: 7,777,097,216 || trainable%: 2.0764
Loading data...
Formatting inputs...Skip in lazy mode
Using /home/caomy/.cache/torch_extensions/py310_cu118 as PyTorch extensions root...
Creating extension directory /home/caomy/.cache/torch_extensions/py310_cu118/fused_adam...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/caomy/.cache/torch_extensions/py310_cu118/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/TH -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data2/caomy/envs/Qqwen2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/TH -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data2/caomy/envs/Qqwen2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/TH -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data2/caomy/envs/Qqwen2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -DBF16_AVAILABLE -c /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data1/caomy/Qwen_information/Qwen2/examples/sft/finetune.py", line 383, in <module>
    train()
  File "/data1/caomy/Qwen_information/Qwen2/examples/sft/finetune.py", line 374, in train
    trainer.train()
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/transformers/trainer.py", line 2015, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1291, in prepare
    result = self._prepare_deepspeed(*args)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/accelerate/accelerator.py", line 1758, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/__init__.py", line 176, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 307, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1230, in _configure_optimizer
    basic_optimizer = self._configure_basic_optimizer(model_parameters)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1307, in _configure_basic_optimizer
    optimizer = FusedAdam(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
    fused_adam_cuda = FusedAdamBuilder().load()
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 479, in load
    return self.jit_load(verbose)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 523, in jit_load
    op_module = load(name=self.name,
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1509, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1624, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1909, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'fused_adam'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3123202) of binary: /data2/caomy/envs/Qqwen2/bin/python
Traceback (most recent call last):
  File "/data2/caomy/envs/Qqwen2/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.0.0', 'console_scripts', 'torchrun')())
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-24_13:48:35
  host      : gpu-15.ld-hadoop.com
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3123202)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by jklj077** [comment]
```
[1/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/TH -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data2/caomy/envs/Qqwen2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/TH -isystem /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /data2/caomy/envs/Qqwen2/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_89,code=sm_89 -gencode=arch=compute_89,code=compute_89 -DBF16_AVAILABLE -U__CUDA_NO_BFLOAT16_OPERATORS__ -U__CUDA_NO_BFLOAT162_OPERATORS__ -std=c++17 -c /data2/caomy/envs/Qqwen2/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc fatal   : Unsupported gpu architecture 'compute_89'
```

Your CUDA compiler version is too old to support your GPU. Follow `https://huggingface.co/docs/transformers/deepspeed#installation` and `https://www.deepspeed.ai/tutorials/advanced-install/`, if you have trouble in configuring the environment or consulting with your system administrator.
