### ISSUE TITLE
qwen2 finetune 报错

### ISSUE THREAD

**Issue by xsank** [QwenLM/Qwen2#708]
```shell
[WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
/home/admin/test/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-06-26 19:51:15,295] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-26 19:51:15,295] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
/home/admin/test/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-06-26 19:51:15,323] [INFO] [comm.py:637:init_distributed] cdb=None
/home/admin/test/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 88443) of binary: /home/admin/test/bin/python3
Traceback (most recent call last):
  File "/home/admin/test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/admin/test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/run.py", line 798, in <module>
    main()
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/admin/test/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
finetune.py FAILED
-----------------------------------------------------
Failures:
[1]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 88444)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88444
[2]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 88445)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88445
[3]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 88446)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88446
[4]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 4 (local_rank: 4)
  exitcode  : -7 (pid: 88447)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88447
[5]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 5 (local_rank: 5)
  exitcode  : -7 (pid: 88448)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88448
[6]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 6 (local_rank: 6)
  exitcode  : -7 (pid: 88449)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88449
[7]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 7 (local_rank: 7)
  exitcode  : -7 (pid: 88450)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88450
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-26_19:51:21
  host      : my-workstation
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 88443)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 88443
=====================================================
```

**Comment by jklj077** [comment]
Please provide steps to reproduce and related package versions (transformers, accelerate, deepspeed, etc.)

**Comment by xsank** [comment]
@jklj077 
```shell
ENV
transformers==4.40.0
accelerate==0.31.0
deepspeed==0.14.3

operation
bash finetune.sh (in qwen2/examples/sft/)
```

**Comment by jklj077** [comment]
Did you use docker or some kind of containers? If so, please consider increasing the size of shared memory.
