### ISSUE TITLE
尝试输出attention信息，报错RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by BryanMurkyChan** [QwenLM/Qwen2#722]
问题描述：
我在做大模型可解释性相关的研究工作，希望输出模型每一层的注意力信息，Llama3可以正常使用generate方法下面的output_attention=True输出，但是这一方法在Qwen2下面出问题了。

源码：
```
import os
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

device = "cuda"  # the device to load the model onto
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

model_path = 'E:/code/Qwen2/model/qwen/Qwen2-7B-Instruct'

try:
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float16,
        device_map="auto",
        attn_implementation="eager"  # specify eager attention implementation
    )
    tokenizer = AutoTokenizer.from_pretrained(model_path)
except Exception as e:
    print(f"Error loading model or tokenizer: {e}")
    exit()

prompt = "Give me a short introduction to large language model."
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": prompt}
]

text = tokenizer.apply_chat_template(
    messages,
    tokenize=False,
    add_generation_prompt=True
)
model_inputs = tokenizer([text], return_tensors="pt").to(device)

# Ensure inputs are valid
if torch.isnan(model_inputs.input_ids).any() or torch.isinf(model_inputs.input_ids).any():
    print("Error: Input contains NaN or Infinity values.")
    exit()

try:
    # Enable output of attention weights
    output = model.generate(
        model_inputs.input_ids,
        max_new_tokens=100,  # reduce the number of tokens to generate
        output_attentions=True,
        return_dict_in_generate=True
    )
    
    generated_ids = output.sequences
    attentions = output.attentions  # Extract the attentions from the output

    # Check for NaN or inf in the output
    if torch.isnan(generated_ids).any() or torch.isinf(generated_ids).any():
        print("Error: Output contains NaN or Infinity values.")
        exit()

    # Post-process the generated ids
    generated_ids = [
        output_ids[len(input_ids):] for input_ids, output_ids in zip(model_inputs.input_ids, generated_ids)
    ]
    
    response = tokenizer.batch_decode(generated_ids, skip_special_tokens=True)[0]
    print("Generated Response:", response)
    
    # Print attentions
    print("\nAttention Weights:")
    for layer_idx, layer_attention in enumerate(attentions):
        print(f"Layer {layer_idx + 1}: {layer_attention}")
        
except Exception as e:
    print(f"Error during generation: {e}")
    # Additional debug information
    import traceback
    traceback.print_exc()
```

报错：
Traceback (most recent call last):
  File "e:\code\Qwen2\trans_test.py", line 42, in <module>
    output = model.generate(
             ^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\transformers\generation\utils.py", line 1525, in generate
    return self.sample(
           ^^^^^^^^^^^^
  File "D:\anaconda\Lib\site-packages\transformers\generation\utils.py", line 2658, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by jklj077** [comment]
Hi, since you have forced the use of "eager" attention implementation within transformers, please consider using [this patch](https://github.com/jklj077/transformers/tree/qwen2-patch).

**Comment by fangyiwb** [comment]
我之前也是报这个错，升级一下torch和transformers解决了
transformers==4.42.4
torch==2.2.2
