### ISSUE TITLE
使用xinference进行chat报错probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by zhaozhizhuo** [QwenLM/Qwen2#750]
User: 你好你是谁
Assistant: Traceback (most recent call last):
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 1258, in model_chat
    loop.run_until_complete(task)
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 1229, in chat_internal
    for chunk in model.chat(
  File "/copydata2/zhaozhizhuo/anaconda3/envs/langchain-xinference/lib/python3.10/site-packages/xinference/client/common.py", line 51, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:46099, pid=845126] probability tensor contains either `inf`, `nan` or element < 0

**Comment by jklj077** [comment]
xinference bundles a lot of backends, and it can use transformers, vllm, llama.cpp, mlx, ... what were you actually using? 

in addition, what models were you using? was it a quantized one? were you using GPU? if so what was the card? how many? what was the driver version? were you running the model in fp16 or bf16? 

we need more information or you could provide steps to reproduce

**Comment by zhaozhizhuo** [comment]
我使用了xinference中transformers的推理，使用了qwen2-7b模型，使用了7张3090共同进行推理。CUDA版本是11.4。我使用了默认参数进行对话，不知道如何查看对应的fp16 or bf16。

下面是未使用xinference进行推理遇到的问题：
现在我在使用git中提供的推理代码时，使用同样的模型进行推理的过程中，仅仅更换了机器，使用完全一致的模型文件，其中一个机器在进行推理的过程中，每一次的推理都会输出类似于如下文本：<|im_end|><|im_start|>assistant，有时出现孟加拉语等小语种，请问是什么原因。

**Comment by jklj077** [comment]
Hi, 

Qwen2-7B is the base or pretrained model which is for finetuning and not for being used directly. Please use Qwen2-7B-Instruct.

However, Qwen2-7B with transformers and bfloat16 should not encounter `probability tensor contains either inf, nan or element < 0` and since you were using multiple GPUs, it could be related to issues of the nvidia driver. Please try upgrading the driver (and pytorch).

FYI, transformers is inefficient with multiple GPUs. Please use vllm for inference on multiple GPUs (7B can be used on 4 GPUs with tensor parallel).
