### ISSUE TITLE
使用past_key_values生成内容时报错

### ISSUE THREAD

**Issue by zzc-1024** [QwenLM/Qwen2#803]
我参考了教程：https://zhuanlan.zhihu.com/p/691365305
使用past_key_values修改生成内容，但是却无法正确生成：
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '2'
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("/models/Qwen2-7B-Instruct")
model = AutoModelForCausalLM.from_pretrained("/models/Qwen2-7B-Instruct", device_map="auto")

input_ids = tokenizer("你好，世界！", return_tensors="pt").to("cuda")

output_1 = model.generate(**input_ids, max_new_tokens=1, return_dict_in_generate=True)
output_tokens_1 = tokenizer.convert_ids_to_tokens(output_1.sequences[0])
output_string_1 = tokenizer.convert_tokens_to_string(output_tokens_1)


new_ids = output_1.sequences[0][len(input_ids.input_ids[0]):]
past_k_v = output_1.past_key_values
new_past_k_v=tuple([((i[0][0][:,:input_ids.input_ids.shape[1],:].unsqueeze(0)),(i[1][0][:,:input_ids.input_ids.shape[1],:].unsqueeze(0))) for i in past_k_v])
input_ids_2 = tokenizer("\n", return_tensors="pt").to("cuda")

# 生成新的attention_mask
new_attention_mask = torch.ones(1, input_ids.input_ids.shape[1]+input_ids_2.input_ids.shape[1]).to('cuda')

# 这里报错了
output_2 = model.generate(input_ids_2.input_ids, attention_mask=new_attention_mask, max_new_tokens=1, return_dict_in_generate=True, past_key_values=new_past_k_v)
```
报错：
```bash
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|█| 4/4 
Some parameters are on the meta device device because they were offloaded to the cpu.
Traceback (most recent call last):
  File "/inner/CSC/test.py", line 22, in <module>
    output_2 = model.generate(input_ids_2.input_ids, attention_mask=new_attention_mask, max_new_tokens=1, return_dict_in_generate=True, past_key_values=new_past_k_v)
  File "/root/anaconda3/envs/CSC/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/CSC/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/anaconda3/envs/CSC/lib/python3.10/site-packages/transformers/generation/utils.py", line 2644, in _sample
    model_kwargs = self._get_initial_cache_position(input_ids, model_kwargs)
  File "/root/anaconda3/envs/CSC/lib/python3.10/site-packages/transformers/generation/utils.py", line 1409, in _get_initial_cache_position
    model_kwargs["cache_position"] = torch.arange(past_length, cur_len, device=input_ids.device)
RuntimeError: upper bound and larger bound inconsistent with step sign
```

**Comment by jklj077** [comment]
hi, please ask the person who wrote that tutorial

**Comment by yunlongia** [comment]
有解决这个问题吗

**Comment by zzc-1024** [comment]
没有...
