### ISSUE TITLE
使用modelscope快速开始，报错

### ISSUE THREAD

**Issue by somePeopleFireAndWood** [QwenLM/Qwen2#904]
Traceback (most recent call last):
  File "D:\work\workplace\qwen\demo.py", line 8, in <module>
    device_map="auto",
  File "D:\work\workplace\qwen\lib\site-packages\modelscope\utils\hf_util.py", line 66, in from_pretrained
    **kwargs)
  File "D:\work\workplace\qwen\lib\site-packages\transformers\models\auto\auto_factory.py", line 461, in from_pretrained
    **kwargs,
  File "D:\work\workplace\qwen\lib\site-packages\transformers\models\auto\configuration_auto.py", line 957, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "D:\work\workplace\qwen\lib\site-packages\transformers\models\auto\configuration_auto.py", line 671, in __getitem__
    raise KeyError(key)
KeyError: 'qwen2'

**Comment by somePeopleFireAndWood** [comment]
python版本不对导致transformers版本不对，导致如上报错。
